version: '3.7'
services:

  fastbot-ros2-real:
    build:
      context: .
      dockerfile: Dockerfile.real
    network_mode: host
    privileged: true
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyACM0:/dev/ttyACM0"
    restart: always

  fastbot-ros2-slam-real:
    build:
      context: .
      dockerfile: Dockerfile.slam
    network_mode: host
    restart: always
