version: '3'
services:
  fastbot-ros2-gazebo:
    image: mathros/mathiasrosas-cp22:fastbot-ros2-gazebo
    container_name: fastbot-ros2-gazebo
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    privileged: true
    networks:
      - fastbot-network
    restart: always
    entrypoint: ["/bin/bash", "-c"]
    command: ["source install/setup.bash && ros2 launch fastbot_gazebo one_fastbot_room.launch.py"]
  
  fastbot-ros2-slam:
    image: mathros/mathiasrosas-cp22:fastbot-ros2-slam
    container_name: fastbot-ros2-slam
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    privileged: true
    networks:
      - fastbot-network
    restart: always
    entrypoint: ["/bin/bash", "-c"]
    command: ["sleep 20 && source install/setup.bash && ros2 launch fastbot_slam navigation.launch.py"]
  
  fastbot-ros2-webapp:
    image: mathros/mathiasrosas-cp22:fastbot-ros2-webapp
    container_name: fastbot-ros2-webapp
    hostname: fastbot-ros2-webapp
    privileged: true
    environment:
      - ROS_DOMAIN_ID=0
    volumes:
      - logs:/var/log/nginx
    networks:
      - fastbot-network
    ports:
      - "7000:80"
      - "9090:9090"
    restart: always

volumes:
  logs: {}
networks:
  fastbot-network:
    driver: bridge